kind: pipeline
name: default
type: docker

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event:
        - tag
        - pull_request

  - name: Build
    image: golang:1.20.4-alpine3.17
    commands:
      - go mod tidy
      - go build -o godl ./cmd/godl/main.go
    when:
      event:
        - pull_request

  - name: release
    image: goreleaser/goreleaser
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - goreleaser release
    when:
      event: tag